export const events = [
  {
    id: 1,
    title: 'People, Planet, Pint: Sustainability Meetup',
    image: '/images/berlin.jpeg',
    description: 'Small99 provides carbon reduction plans for micro and small businesses. With a simple measurement tool, Small99 empowers the businesses to start their sustainability journey.',
    location: 'Berlin, Germany'
  },
  {
    id: 2,
    title: 'The World Happiness Summit',
    image: '/images/summit.jpeg',
    description: 'The 6th annual World Happiness Summit will take place in the UK for the first time! Lets celebrate International Day of Happiness together. Sustainable Growth – Nutrition - Beyond GDP',
    location: 'London, UK'
  },
  {
    id: 3,
    title: 'Green, Sustainable Energy Happy Hour',
    image: '/images/green.jpeg',
    description: 'Devoted to professionals in the Green, Sustainable Energy and Environment; to grow, interact, and learn from each other.',
    location: 'Washington, USA'
  },
  {
    id: 4,
    title: 'Campaign for Nature',
    image: '/images/earth.jpeg',
    description: 'This program is one in a continuing series sponsored by the Climate Action Group of the Federated Garden Clubs of Maryland.',
    location: 'Maryland, USA'
  },
];




export const lineChartData = [
  { date: "Oct", score: 14000 },
  { date: "Nov", score: 13000 },
  { date: "Dec", score: 15000 },
  { date: "Jan", score: 12000 },
  { date: "Feb", score: 13000 },
  { date: "March", score: 10000 }
];



export const appliances = {
  "42 inch plasma tv": { "min": 450, "max": 600, "standby": null },
  "55 inch led tv": { "min": 58, "max": 150, "standby": 1 },
  "light bulb (incandescent)": { "min": 60, "max": 100, "standby": 0 },
  "air cooler": { "min": 65, "max": 80, "standby": null },
  "air fryer": { "min": 1500, "max": 1500, "standby": null },
  "air purifier": { "min": 25, "max": 30, "standby": null },
  "amazon echo": { "min": 3, "max": 3, "standby": 2 },
  "amazon echo dot": { "min": 2, "max": 3, "standby": null },
  "amazon echo show": { "min": 2, "max": 4, "standby": 0.1 },
  "american-style fridge freezer": { "min": 40, "max": 80, "standby": null },
  "apple tv": { "min": 3, "max": 6, "standby": 0.3 },
  "aquarium pump": { "min": 20, "max": 50, "standby": null },
  "av receiver": { "min": 450, "max": 450, "standby": null },
  "bathroom towel heater": { "min": 60, "max": 150, "standby": null },
  "ceiling fan": { "min": 60, "max": 70, "standby": 0 },
  "chromebook": { "min": 45, "max": 45, "standby": null },
  "chromecast": { "min": 2, "max": 2, "standby": null },
  "clock radio": { "min": 1, "max": 2, "standby": null },
  "clothes dryer": { "min": 1000, "max": 4000, "standby": null },
  "coffee maker": { "min": 800, "max": 1400, "standby": null },
  "computer monitor": { "min": 25, "max": 30, "standby": null },
  "cooker hood": { "min": 20, "max": 30, "standby": 0 },
  "corded drill": { "min": 600, "max": 850, "standby": null },
  "corded electric handheld leaf blower": { "min": 2500, "max": 2500, "standby": null },
  "cordless drill charger": { "min": 70, "max": 150, "standby": null },
  "cpap machine": { "min": 30, "max": 60, "standby": null },
  "curling iron": { "min": 25, "max": 35, "standby": 0 },
  "dab mains radio": { "min": 5, "max": 9, "standby": null },
  "deep freezer": { "min": 19, "max": 19, "standby": null },
  "dehumidifier": { "min": 240, "max": 240, "standby": null },
  "desk lamp": { "min": 40, "max": 65, "standby": null },
  "desktop computer": { "min": 100, "max": 450, "standby": null },
  "dishwasher": { "min": 1200, "max": 1500, "standby": null },
  "domestic water pump": { "min": 200, "max": 300, "standby": 0 },
  "dvd player": { "min": 26, "max": 60, "standby": null },
  "electric blanket": { "min": 200, "max": 200, "standby": null },
  "electric boiler": { "min": 4000, "max": 14000, "standby": null },
  "doorbell": { "min": 2, "max": 2, "standby": null },
  "electric heater fan": { "min": 2000, "max": 3000, "standby": null },
  "electric kettle": { "min": 1200, "max": 3000, "standby": 0 },
  "electric mower": { "min": 1500, "max": 1500, "standby": null },
  "electric pressure cooker": { "min": 1000, "max": 1000, "standby": null },
  "electric shaver": { "min": 15, "max": 20, "standby": null },
  "electric stove": { "min": 2000, "max": 2000, "standby": null },
  "electric tankless water heater": { "min": 6600, "max": 8800, "standby": null },
  "electric thermal radiator": { "min": 500, "max": 500, "standby": null },
  "electric toothbrush charger": { "min": 6, "max": 6, "standby": null },
  "espresso coffee machine": { "min": 1300, "max": 1500, "standby": null },
  "ev car charger": { "min": 2000, "max": 7000, "standby": null },
  "ev home charger": { "min": 1600, "max": 3400, "standby": null },
  "evaporative air conditioner": { "min": 2600, "max": 2600, "standby": null },
  "external hard drive": { "min": 1, "max": 3, "standby": null },
  "extractor fan": { "min": 12, "max": 12, "standby": null },
  "fluorescent lamp": { "min": 28, "max": 45, "standby": null },
  "food blender": { "min": 300, "max": 400, "standby": null },
  "food dehydrator": { "min": 800, "max": 800, "standby": null },
  "freezer": { "min": 30, "max": 50, "standby": null },
  "fridge": { "min": 100, "max": 220, "standby": null },
  "fryer": { "min": 1000, "max": 1000, "standby": null },
  "game console": { "min": 120, "max": 200, "standby": null },
  "gaming pc": { "min": 300, "max": 600, "standby": 1 },
  "garage door opener": { "min": 300, "max": 400, "standby": null },
  "google home mini": { "min": 15, "max": 15, "standby": 2 },
  "guitar amplifier": { "min": 20, "max": 30, "standby": null },
  "hair blow dryer": { "min": 1800, "max": 2500, "standby": null },
  "hand wash oversink water heater": { "min": 3000, "max": 3000, "standby": null },
  "heated bathroom mirror": { "min": 50, "max": 100, "standby": null },
  "heated hair rollers": { "min": 400, "max": 400, "standby": null },
  "home air conditioner": { "min": 1000, "max": 4000, "standby": null },
  "home internet router": { "min": 5, "max": 15, "standby": null },
  "home phone": { "min": 3, "max": 5, "standby": 2 },
  "home sound system": { "min": 95, "max": 95, "standby": 1 },
  "hot water dispenser": { "min": 1200, "max": 1300, "standby": null },
  "hot water immersion heater": { "min": 3000, "max": 3000, "standby": null },
  "humidifier": { "min": 35, "max": 40, "standby": null },
  "imac": { "min": 60, "max": 240, "standby": 1 },
  "induction hob (per hob)": { "min": 1400, "max": 1800, "standby": null },
  "inkjet printer": { "min": 20, "max": 30, "standby": null },
  "inverter air conditioner": { "min": 1300, "max": 1800, "standby": null },
  "iron": { "min": 1000, "max": 1000, "standby": null },
  "jacuzzi": { "min": 3000, "max": 7500, "standby": 1500 },
  "kitchen extractor fan": { "min": 200, "max": 200, "standby": null },
  "laptop computer": { "min": 50, "max": 100, "standby": null },
  "laser printer": { "min": 600, "max": 800, "standby": null },
  "lawnmower": { "min": 1000, "max": 1400, "standby": null },
  "led christmas lights": { "min": 5, "max": 5, "standby": null },
  "led light bulb": { "min": 7, "max": 10, "standby": 0 },
  "lg soundbar": { "min": 23, "max": 30, "standby": 0.5 },
  "mi box": { "min": 5, "max": 7, "standby": 3 },
  "microwave": { "min": 600, "max": 1700, "standby": 3 },
  "night light": { "min": 1, "max": 1, "standby": 0 },
  "nintendo switch ac adapter": { "min": 7, "max": 40, "standby": null },
  "outdoor hot tub": { "min": 60, "max": 500, "standby": null },
  "oven": { "min": 2150, "max": 2150, "standby": null },
  "paper shredder": { "min": 200, "max": 220, "standby": null },
  "pedestal fan": { "min": 50, "max": 60, "standby": null },
  "percolator": { "min": 800, "max": 1100, "standby": null },
  "philips hue smart bulb": { "min": 8, "max": 9, "standby": 0.4 },
  "phone charger": { "min": 4, "max": 7, "standby": null },
  "playstation 4": { "min": 85, "max": 90, "standby": null },
  "playstation 5": { "min": 160, "max": 200, "standby": null },
  "portable air conditioner": { "min": 1000, "max": 1200, "standby": null },
  "power shower": { "min": 7500, "max": 10500, "standby": 0 },
  "pressure cooker": { "min": 700, "max": 700, "standby": null },
  "pressure washer": { "min": 1500, "max": 1500, "standby": null },
  "projector": { "min": 220, "max": 270, "standby": 1 },
  "refrigerator": { "min": 100, "max": 200, "standby": null },
  "rice cooker": { "min": 200, "max": 800, "standby": null },
  "ring spotlight cam wired": { "min": 25, "max": 4, "standby": 2 },
  "sandwich maker": { "min": 700, "max": 1000, "standby": null },
  "scanner": { "min": 10, "max": 18, "standby": null },
  "set top box": { "min": 27, "max": 30, "standby": null },
  "sewing machine": { "min": 70, "max": 80, "standby": null },
  "singer sewing machine": { "min": 100, "max": 100, "standby": null },
  "sky q 2tb box": { "min": 40, "max": 40, "standby": null },
  "slow cooker": { "min": 160, "max": 180, "standby": null },
  "smoke detector": { "min": 0, "max": 1, "standby": null },
  "soldering iron": { "min": 30, "max": 60, "standby": null },
  "space heater": { "min": 2000, "max": 5000, "standby": null },
  "steam iron": { "min": 2200, "max": 2500, "standby": null },
  "steriliser": { "min": 650, "max": 650, "standby": null },
  "straightening iron": { "min": 75, "max": 300, "standby": null },
  "strimmer": { "min": 300, "max": 500, "standby": null },
  "submersible water pump": { "min": 200, "max": 400, "standby": null },
  "table fan": { "min": 10, "max": 25, "standby": null },
  "table top fridge": { "min": 10, "max": 15, "standby": null },
  "tablet charger": { "min": 10, "max": 15, "standby": null },
  "tablet computer": { "min": 5, "max": 10, "standby": null },
  "toaster": { "min": 800, "max": 1800, "standby": 0 },
  "tower fan": { "min": 60, "max": 60, "standby": null },
  "treadmill": { "min": 280, "max": 900, "standby": null },
  "tube light (1500mm)": { "min": 22, "max": 22, "standby": null },
  "vacuum cleaner": { "min": 450, "max": 900, "standby": 0 },
  "wall fan": { "min": 45, "max": 60, "standby": 0 },
  "washing machine": { "min": 500, "max": 500, "standby": 1 },
  "water dispenser": { "min": 100, "max": 100, "standby": null },
  "water feature": { "min": 35, "max": 35, "standby": null },
  "water filter and cooler": { "min": 70, "max": 100, "standby": null },
  "wifi booster": { "min": 1, "max": 2, "standby": null },
  "wifi router": { "min": 4, "max": 10, "standby": 4 },
  "window air conditioner": { "min": 500, "max": 1500, "standby": null },
  "wine cooler (18 bottles)": { "min": 83, "max": 83, "standby": 0 },
  "xbox one": { "min": 50, "max": 110, "standby": 14 }
};


export const calculatorAppliances = {
  "Led TV": { "max": 150 },
  "60w Light Bulb": { "max": 60 },
  "100w Light Bulb": { "max": 100 },
  "Air Conditioner": { "max": 2600 },
  "Air Fryer": { "max": 1500 },
  "Coffee Maker": { "max": 1400 },
  "Food Blender": { "max": 400 },
  "Rice Cooker": { "max": 800 },
  "Water Dispenser": { "max": 100 },
  "Freezer": { "max": 50 },
  "Fridge": { "max": 220 },
  "Dishwasher": { "max": 1500 },
  "Air Purifier": { "max": 30 },
  "Amazon Echo": { "max": 3 },
  "Washing Machine": { "max": 500 },
  "Clothes Dryer": { "max": 4000 },
  "Desktop Computer": { "max": 450 },
  "Hair Blow Dryer": { "max": 2500 },
  "Laptop": { "max": 100 },
  "Laser Printer": { "max": 800 },
  "Xbox One": { "max": 110 }
};